/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 one_piece_nico_robin.glb -t 
Author: Tigerar1 (https://sketchfab.com/allanromanreyes)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/one-piece-nico-robin-96f89bbd2c2543c989c04a4d3e54891a
Title: One Piece Nico Robin
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    MI_P007_E001_Body_CS01: THREE.MeshStandardMaterial
    MI_P007_E001_Face_CS01: THREE.MeshStandardMaterial
    MI_P007_E001_Hair_CS01: THREE.MeshStandardMaterial
    MI_P007_E001_Iris_CS01: THREE.MeshStandardMaterial
    MI_P007_E001_Wear_CS01: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Robin(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/one_piece_nico_robin.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MI_P007_E001_Body_CS01} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MI_P007_E001_Face_CS01} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MI_P007_E001_Hair_CS01} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MI_P007_E001_Iris_CS01} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.MI_P007_E001_Wear_CS01} />
      </group>
    </group>
  )
}

useGLTF.preload('/one_piece_nico_robin.glb')
